replicaCount: 1

image:
  repository: rabbitmq
  tag: 3.13-management-alpine

auth:
  username: userrabbit
  password: itk123@
  erlangCookie: mysecretcookie

service:
  type: ClusterIP

ingress:
  enabled: false


resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 250m

persistence:
  enabled: true
  size: 5Gi
  storageClassName: "hcloud-volumes"
